[package]
name = "long_print"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
libusb = "0.3"
escposify = { git = "https://github.com/Masterchef365/rust-escposify" }
image = "0.21"
dither = "1.3.7"
failure = "0.1.6"
